/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.BorderLayout;

/**
 *
 * @author USUARIO
 */
public class frmMenu extends javax.swing.JFrame {

    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnSistema = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnAjuda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("SISTEMA INTEGRADO DE GESTÃO COMERCIAL"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel3.setBackground(new java.awt.Color(22, 90, 112));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 600));

        jPanel4.setBackground(new java.awt.Color(22, 90, 112));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        btnSistema.setBackground(new java.awt.Color(0, 58, 76));
        btnSistema.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-cart-free-icon-font.png"))); // NOI18N
        btnSistema.setText("SISTEMA");
        btnSistema.setBorder(null);
        btnSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistema.setFocusPainted(false);
        btnSistema.setPreferredSize(new java.awt.Dimension(200, 50));
        btnSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSistema);

        btnCadastro.setBackground(new java.awt.Color(0, 58, 76));
        btnCadastro.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-free-icon-font.png"))); // NOI18N
        btnCadastro.setText("CADASTRO");
        btnCadastro.setBorder(null);
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.setFocusPainted(false);
        btnCadastro.setPreferredSize(new java.awt.Dimension(200, 50));
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastro);

        btnConsulta.setBackground(new java.awt.Color(0, 58, 76));
        btnConsulta.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-free-icon-font.png"))); // NOI18N
        btnConsulta.setText("CONSULTA");
        btnConsulta.setBorder(null);
        btnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta.setFocusPainted(false);
        btnConsulta.setPreferredSize(new java.awt.Dimension(200, 50));
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel3.add(btnConsulta);

        btnRelatorio.setBackground(new java.awt.Color(0, 58, 76));
        btnRelatorio.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document-free-icon-font.png"))); // NOI18N
        btnRelatorio.setText("RELATÓRIOS");
        btnRelatorio.setBorder(null);
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel3.add(btnRelatorio);

        btnCompra.setBackground(new java.awt.Color(0, 58, 76));
        btnCompra.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck-loading-free-icon-font.png"))); // NOI18N
        btnCompra.setText("COMPRAS");
        btnCompra.setBorder(null);
        btnCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompra.setFocusPainted(false);
        btnCompra.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel3.add(btnCompra);

        btnEstoque.setBackground(new java.awt.Color(0, 58, 76));
        btnEstoque.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boxes-free-icon-font.png"))); // NOI18N
        btnEstoque.setText("ESTOQUE");
        btnEstoque.setBorder(null);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setFocusPainted(false);
        btnEstoque.setPreferredSize(new java.awt.Dimension(200, 50));
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        jPanel3.add(btnEstoque);

        btnAjuda.setBackground(new java.awt.Color(0, 58, 76));
        btnAjuda.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        btnAjuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/interrogation-free-icon-font.png"))); // NOI18N
        btnAjuda.setText("AJUDA");
        btnAjuda.setBorder(null);
        btnAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjuda.setFocusPainted(false);
        btnAjuda.setPreferredSize(new java.awt.Dimension(200, 50));
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAjuda);

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(0, 58, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(0, 58, 77));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fonte-de-icone-de-user-gratis.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 60));
        jPanel5.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Olá,");
        jPanel5.add(jLabel3);

        lblUser.setFont(new java.awt.Font("Abel", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Fulano");
        jPanel5.add(lblUser);

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaActionPerformed
        // TODO add your handling code here:
        frmPDV pdv = new frmPDV();
        
        pnlCenter.removeAll();
        pnlCenter.add(pdv, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_btnSistemaActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        frmCadGeral cadgeral = new frmCadGeral();
        
        pnlCenter.removeAll();
        pnlCenter.add(cadgeral, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
        pnlCenter.setVisible(true);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        frmConsulta consulta = new frmConsulta();
        
        pnlCenter.removeAll();
        pnlCenter.add(consulta, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
        pnlCenter.setVisible(true);
        
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        frmEstoque estoque = new frmEstoque();
        
        pnlCenter.removeAll();
        pnlCenter.add(estoque, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
        pnlCenter.setVisible(true);
        
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // TODO add your handling code here:
        frmAjuda ajuda = new frmAjuda();
        
        pnlCenter.removeAll();
        pnlCenter.add(ajuda, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
        pnlCenter.setVisible(true);
    }//GEN-LAST:event_btnAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSistema;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lblUser;
    public javax.swing.JPanel pnlCenter;
    // End of variables declaration//GEN-END:variables
}
