/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.BorderLayout;

/**
 *
 * @author USUARIO
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu2
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        btnCaixa = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTop.setBackground(new java.awt.Color(0, 58, 77));
        pnlTop.setPreferredSize(new java.awt.Dimension(900, 100));
        pnlTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        btnCaixa.setBackground(new java.awt.Color(0, 58, 77));
        btnCaixa.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        btnCaixa.setForeground(new java.awt.Color(255, 255, 255));
        btnCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cash-register-free-icon-font.png"))); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.setBorder(null);
        btnCaixa.setBorderPainted(false);
        btnCaixa.setFocusPainted(false);
        btnCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaixa.setIconTextGap(5);
        btnCaixa.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        pnlTop.add(btnCaixa);

        btnClientes.setBackground(new java.awt.Color(0, 58, 77));
        btnClientes.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fonte-de-icone-de-user-gratis.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setFocusPainted(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setIconTextGap(5);
        btnClientes.setPreferredSize(new java.awt.Dimension(100, 100));
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnlTop.add(btnClientes);

        btnProdutos.setBackground(new java.awt.Color(0, 58, 77));
        btnProdutos.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        btnProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/boxes-free-icon-font.png"))); // NOI18N
        btnProdutos.setText("Produtos");
        btnProdutos.setBorder(null);
        btnProdutos.setBorderPainted(false);
        btnProdutos.setFocusPainted(false);
        btnProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdutos.setIconTextGap(5);
        btnProdutos.setPreferredSize(new java.awt.Dimension(100, 100));
        btnProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        pnlTop.add(btnProdutos);

        btnRelatorios.setBackground(new java.awt.Color(0, 58, 77));
        btnRelatorios.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-free-icon-font.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setBorder(null);
        btnRelatorios.setBorderPainted(false);
        btnRelatorios.setFocusPainted(false);
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setIconTextGap(5);
        btnRelatorios.setPreferredSize(new java.awt.Dimension(100, 100));
        btnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        pnlTop.add(btnRelatorios);

        btnCompras.setBackground(new java.awt.Color(0, 58, 77));
        btnCompras.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/truck-loading-free-icon-font.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setBorder(null);
        btnCompras.setBorderPainted(false);
        btnCompras.setFocusPainted(false);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setIconTextGap(5);
        btnCompras.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        pnlTop.add(btnCompras);

        btnEstoque.setBackground(new java.awt.Color(0, 58, 77));
        btnEstoque.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/boxes-free-icon-font.png"))); // NOI18N
        btnEstoque.setText("Estoque");
        btnEstoque.setBorder(null);
        btnEstoque.setBorderPainted(false);
        btnEstoque.setFocusPainted(false);
        btnEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstoque.setIconTextGap(5);
        btnEstoque.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        pnlTop.add(btnEstoque);

        getContentPane().add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        frmMenucli menucli = new frmMenucli();
        
        pnlCenter.removeAll();
        pnlCenter.add(menucli, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        frmMenupro menupro = new frmMenupro();
        
        pnlCenter.removeAll();
        pnlCenter.add(menupro, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        // TODO add your handling code here:
        frmPDV pdv = new frmPDV();
        
        pnlCenter.removeAll();
        pnlCenter.add(pdv);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
        frmMenurela menurel = new frmMenurela();
        
        pnlCenter.removeAll();
        pnlCenter.add(menurel, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
        frmMenucompra menucom = new frmMenucompra();
        
        pnlCenter.removeAll();
        pnlCenter.add(menucom, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        frmMenuestoque menuestq = new frmMenuestoque();
        
        pnlCenter.removeAll();
        pnlCenter.add(menuestq, BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
